### ISSUE TITLE
Gravity calculation is not natural

### ISSUE THREAD

**Issue by vicksonzero** [xem/mini2DPlatformer#1]
Hi thank you for letting me use your project as a minimal platformer starter.

just a comment on the custom physics:
https://github.com/xem/mini2DPlatformer/blob/c7036a3ad72982ec87128c63c9c4ff28f50cd0ad/index.html#L75-L76

here, adding g to the acceleration makes the player drop at increasing acceleration, aka going cubic instead of parabola

I believe the correct way is to add `g` to `hero_vy` every frame instead. Like this:

```
-  hero_ay += g;
+  hero_vy += g;
   hero_vy += hero_ay;
```

**Comment by xem** [comment]
Hey, thanks a lot, I think you're right (i'm not expert in these formulae and didn't realize it was weird :p 
I'll include both implementations in the code / comments so people can choose between them :)

**Comment by vicksonzero** [comment]
again thank you very much for saving me at least 6 hours of work.

do you want me to send a pull request after the js13k jam?

**Comment by xem** [comment]
you're welcome, it took me about one hour to make :)
I'm very busy with my game right now but sure, I'll gladly accept your PR!

**Comment by vicksonzero** [comment]
(off topic)
seriously? that level of details in 1 hour is pretty impressive. you must be very familiar with implementing custom platformer movements.

**Comment by xem** [comment]
I made tiny platformers before, especially this 1kb mario1-1 clone, which was an inspiration when making this https://xem.github.io/codegolf/smb11k.html
